### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by MaheshPrayaga**
Removed all typos and grammatical mistakes.
Also added Basic Time complexity notes/

### CODE REVIEW

**Review by shreeshailaya — APPROVED** [review]

**Review by shreeshailaya — COMMENTED** [review]
The code should be in java because the whole notes of DS are in java code.

**Comment by shreeshailaya** [comment]
I'm closing this because of the given reason...

**Comment by MaheshPrayaga** [comment]
Hey, Vitkar.

          I am Mahesh. Today i made my first contribution, Thanks for
approving it. I get why you closed it. I just wanted to ask you an another
question, Which is, If i made four Pull requests about completing four
sorting algorithms, is that okay? or is there a rule that says i should
make them all in one single PR? Also, i want to know if i can make
atleast two PRs, 1 being a typo clearer and 2 being making the notes.
please help this noob contributor out.

**Comment by shreeshailaya** [comment]
hello @MaheshPrayaga, thank you for your great efforts, but before contributing first read the issue properly **Write notes about Time and Space Complexity in Data Structure** #115 so that you have to write notes on **time and space** complexity also need to write programs which are in java and the programs should be in code quote like ```java  <your code will be here>``` (google how to write java code in GitHub readme.md )

**Pull request closed without merging**
