### PR TITLE
Python Django Done

### PR DESCRIPTION
**Pull request by larrikin-coder**
Added Python Django In the readme file with the repo links.

### CODE REVIEW

**Comment by shreeshailaya** [comment]
Hello @larrikin-coder could you please check the below link?

`[✖] %22https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Python%22 → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/"https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Python"'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/github/workspace/"https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Python"'
}`

**Review by shreeshailaya — CHANGES_REQUESTED** [review]
Check out the broken link

**Comment by larrikin-coder** [comment]
Sure

**Review by shreeshailaya — COMMENTED** [review]
Hello  @larrikin-coder 
Check the following link which has status 400/404 modify this link 
`  
  [✖] %22https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Python%22 → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/"https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Python"'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/github/workspace/"https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Python"'
}`

**Comment by larrikin-coder** [comment]
No broken links found in my file , please send the line number with the broken link. @shreeshailaya

**Comment by larrikin-coder** [comment]
please review and accept PR.

**Comment by larrikin-coder** [comment]
Please approve the PR.

**Review by shreeshailaya — APPROVED** [review]

**Pull request merged**
