### PR TITLE
Adding Bubble Sort Algorithm to Datastructure ReadMe file

### PR DESCRIPTION
**Pull request by santhos-13**

### CODE REVIEW

**Review by shreeshailaya — CHANGES_REQUESTED** [review]
The images should be downloaded and should be in the media folder - [this folder](https://github.com/shreeshailaya/C-DAC-Notes/tree/main/Data%20structure/Media)

**Comment by santhos-13** [comment]
@shreeshailaya ok will do it

**Comment by santhos-13** [comment]
@shreeshailaya completed the requested changes.

**Comment by shreeshailaya** [comment]
image
@santhos-13 refer to this screenshot images URLs are not mentioned properly please open a new PR. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/shreeshailaya/C-DAC-Notes/blob/4160975f55c3401a194ade4abc3dd4d244c3cf5f/CONTRIBUTING.md) and [code of conduct](https://github.com/shreeshailaya/C-DAC-Notes/blob/4160975f55c3401a194ade4abc3dd4d244c3cf5f/CODE_OF_CONDUCT.md).

**Pull request closed without merging**
